kind: ZarfPackageConfig
metadata:
  name: traefik
  description: zarf package for traefik
  version: 0.0.1
components:
  - name: traefik
    required: true
    charts:
      - name: traefik
        namespace: traefik
        version: 30.1.0
        url: https://traefik.github.io/charts
        valuesFiles:
          - values.yaml
    actions:
      onDeploy:
        before:
          - cmd: ./zarf tools kubectl create namespace traefik --dry-run=client -o yaml | ./zarf tools kubectl apply -f -
